@startuml solution
title Architecture de la solution

package "Client" {
  [Navigateur]
}

database "API" {
  [Serveur API]
}

package "Base de données" {
  database "Local Storage" {
    [LocalStorage]
  }
}

[Navigateur] --> [Serveur API] : Requêtes HTTP
[Serveur API] --> [LocalStorage] : Requêtes SQL
@enduml
